
services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script inicial (opcional)
    networks:
      - app-network

  # Aplicação Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-myuser}:${POSTGRES_PASSWORD:-mypassword}@postgres:5432/${POSTGRES_DB:-mydatabase}?schema=public
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src:ro # Para desenvolvimento (remover em produção)
    networks:
      - app-network
    command: sh -c "npx prisma db push && npm start"

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge