FROM node:lts-alpine3.22

# Instalar dependências do sistema
RUN apk add --no-cache openssl

WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar TODAS as dependências (incluindo dev)
RUN npm install

# Instalar ts-node globalmente para desenvolvimento
RUN npm install -g ts-node nodemon

# Copiar arquivos do Prisma
COPY prisma ./prisma

# Gerar cliente Prisma
RUN npx prisma generate

# Copiar tsconfig
COPY tsconfig.json ./

# NÃO compila aqui porque vamos usar ts-node em desenvolvimento

EXPOSE 3000

# Comando padrão para desenvolvimento
CMD ["npm", "run", "dev"]